# Generated by Django 4.2 on 2023-05-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_message_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='account',
            new_name='poster',
        ),
    ]
