# Generated by Django 4.2 on 2023-05-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_account_message_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='poster',
        ),
    ]
