# Generated by Django 4.2 on 2023-05-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_request_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='parlevel',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
