# Generated by Django 4.2 on 2023-05-03 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_parlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
