# Generated by Django 4.2 on 2023-05-19 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_expdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['expdate']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-subdate']},
        ),
    ]
